[package]
name = "{{project-name}}-cli"
version = "0.0.1"
edition = "2021"
publish = false

[[bin]]
name = "db"
path = "src/bin/db.rs"

[[bin]]
name = "generate"
path = "src/bin/generate.rs"

[dependencies]
pacesetter = { workspace = true }
{{project-name}}-config = { path = "../config" }
tokio = { version = "1.34", features = ["full"] }
