name: Build

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: Build Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --dry-run
      - run: cargo build -r
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./target/release/gerust
            ./target/package/gerust-*.crate
